language: java

dist: trusty

cache:
  directories:
    - $HOME/.m2

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
  - mvn test -B

notifications:
  email:
    on_success: never
    on_failure: change
